name: Install Wireshark headers (Unix)
runs:
  using: 'composite'
  steps:
    - name: Configure Wireshark
      run: |
        mkdir wireshark/build
        cmake -G Ninja -B wireshark/build -S wireshark -DENABLE_CCACHE=Yes -DENABLE_WERROR=ON -DDISABLE_WERROR=OFF
      shell: bash
    - name: Install headers
      id: install_headers
      run: sudo ninja -C wireshark/build install-headers
      continue-on-error: true
      shell: bash
    # Install headers is not available in older versions, use the full installation instead
    - name: Install Wireshark
      id: install_wireshark
      if: ${{ steps.install_headers.outcome == 'failure' }}
      run: |
        ninja -C wireshark/build
        sudo ninja -C wireshark/build install
      shell: bash